id: AD660A208
title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:14:20.208202
  last_modified_at: 2022-03-01 02:14:20.208231
